apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: web
          image: 714228767476.dkr.ecr.us-east-1.amazonaws.com/web:nginx-1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
