apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: jmolguedSf01/nginx-container
    ports:
    - containerPort: 80
    - containerPort: 443


