FROM debian:latest

RUN apt update -y && \
    apt install -y nginx && \
    mkdir -p /etc/nginx/conf.d /etc/ssl/private && \
    chmod 755 /etc/nginx/conf.d /etc/ssl/private

COPY nginx.conf /etc/nginx/nginx.conf
COPY server.conf /etc/nginx/conf.d/server.conf
COPY ca_bundle.crt /etc/ssl/certs/ca_bundle.crt
COPY private.key /etc/ssl/private/private.key
COPY index.html /etc/nginx/html/index.html
COPY indexingles.html /etc/nginx/html/en/index.html
COPY errores.html /etc/nginx/html/errores.html
CMD ["nginx", "-g", "daemon off;"]
