---
- name: Configurar y ejecutar NGINX en contenedor Docker remoto
  hosts: web
  become: true

  tasks:
    - name: Asegurar que Docker está corriendo
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Copiar pagina web
      ansible.builtin.copy:
        src: /home/debian/webAmazon/templates/index.html.j2
        dest: /home/jorge/web/index.html
        owner: root
        group: root
        mode: "0644"

    - name: Copiar pagina web en ingles
      ansible.builtin.copy:
        src: /home/debian/webAmazon/templates/indexingles.html.j2
        dest: /home/jorge/web/indexingles.html
        owner: root
        group: root
        mode: "0644"

    - name: Copiar pagina web de errores
      ansible.builtin.copy:
        src: /home/debian/webAmazon/templates/errores.html.j2
        dest: /home/jorge/web/errores.html
        owner: root
        group: root
        mode: "0644"



    - name: Copiar Dockerfile al servidor remoto
      ansible.builtin.copy:
        src: /home/debian/webAmazon/templates/Dockerfile.j2
        dest: /home/jorge/web/Dockerfile
        owner: root
        group: root
        mode: "0644"

    - name: Subir archivo de configuración de NGINX
      ansible.builtin.copy:
        src: /home/debian/webAmazon/templates/default.conf.j2
        dest: /home/jorge/web/nginx.conf
        owner: root
        group: root
        mode: '0644'

    - name: Subir archivo server
      ansible.builtin.copy:
        src: /home/debian/webAmazon/templates/server.conf.j2
        dest: /home/jorge/web/server.conf
        owner: root
        group: root
        mode: '0644'

    - name: Subir certificado SSL
      ansible.builtin.copy:
        src: /etc/ssl/certs/certificate.crt
        dest: /home/jorge/web/ca_bundle.crt
        owner: root
        group: root
        mode: '0644'

    - name: Subir clave privada SSL
      ansible.builtin.copy:
        src: /etc/ssl/private/private.key
        dest: /home/jorge/web/private.key
        owner: root
        group: root
        mode: '0600'

    - name: Detener y eliminar contenedor existente (si existe)
      ansible.builtin.command:
        cmd: docker rm -f https-jorge
      ignore_errors: true

    - name: Construir imagen Docker
      ansible.builtin.command:
        cmd: docker build -t https-jorge /home/jorge/web/

    - name: Lanzar contenedor Docker para NGINX
      ansible.builtin.command:
        cmd: >
          docker run -d -p 443:443 -p 80:80
           --name https-jorge https-jorge


    - name: Etiquetar la imagen de subida
      ansible.builtin.command:
        cmd: >
          docker tag https-jorge:latest 714228767476.dkr.ecr.us-east-1.amazonaws.com/web:nginx-1

    - name: Subir la imagen a ECR de Amazon
      ansible.builtin.command:
        cmd: >
          docker push 714228767476.dkr.ecr.us-east-1.amazonaws.com/web:nginx-1
