name: terraform destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Terraform Files
        run: ls -l ./ftp_ldap

      - name: Remove Terraform Cache
        run: rm -rf .terraform .terraform.lock.hcl
        working-directory: ./ftp_ldap

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: Download Terraform State from S3
        run: aws s3 cp s3://artefactos-jorge/terraform_state.tfstate ./ftp_ldap/terraform.tfstate

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./ftp_ldap

      - name: Validate Terraform Plugins
        run: terraform providers
        working-directory: ./ftp_ldap

      - name: Run Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./ftp_ldap

      - name: Delete Terraform State File from S3
        run: aws s3 rm s3://artefactos-jorge/terraform_state.tfstate
