name: terraform destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: Download Terraform State from S3
        run: aws s3 cp s3://artefactos-jorge/terraform_state.tfstate ./ftp_ldap/terraform.tfstate

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./ftp_ldap

      - name: Run Terraform Destroy
        run: |
          terraform destroy -auto-approve \
            -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" \
            -var "public_key=${{ secrets.SSH_PUBLIC_KEY }}"
        working-directory: ./ftp_ldap

      - name: Verify if Terraform State File Exists on S3
        run: |
          aws s3 ls s3://artefactos-jorge/terraform_state.tfstate || echo "File does not exist"
        
      - name: Delete Terraform State File from S3
        run: |
          echo "Attempting to delete terraform_state.tfstate from S3"
          aws s3 rm s3://artefactos-jorge/terraform_state.tfstate || echo "Error deleting file"
        
      - name: Confirm deletion of Terraform State File from S3
        run: |
          aws s3 ls s3://artefactos-jorge/terraform_state.tfstate || echo "File successfully deleted or does not exist"
