name: terraform destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Configuración de credenciales de AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      # Paso 3: Instalar Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      # Paso 4: Inicializar Terraform (que configurará el backend remoto)
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./conexion_VPC

      # Paso 5: Ejecutar Terraform Destroy
      - name: Run Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./conexion_VPC

      # Paso 6: Eliminar el archivo terraform_state desde S3 (si es necesario)
      - name: Delete Terraform State File from S3
        run: |
          echo "Deleting terraform_state from S3..."
          aws s3 rm s3://artefacto-ftp/terraform_state.tfstate || { echo "Failed to delete terraform_state.tfstate from S3"; exit 1; }
