name: terraform destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      # Descargar el archivo terraform_state desde S3, asegurándonos de que la ruta sea correcta
      - name: Download Terraform State from S3
        run: |
          echo "Downloading terraform_state from S3..."
          aws s3 cp s3://artefacto-tf/terraform_state.tfstate ./conexion_VPC/terraform_state.tfstate || { echo "Failed to download terraform_state.tfstate from S3"; exit 1; }

      # Verificar si el archivo terraform_state.tfstate ha sido descargado correctamente
      - name: Verify Terraform State File Download
        run: |
          if [ ! -f ./conexion_VPC/terraform_state.tfstate ]; then
            echo "Terraform state file not found!"
            exit 1
          fi

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      # Inicializar Terraform en el directorio correcto
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./conexion_VPC

      # Ejecutar Terraform Destroy para destruir los recursos
      - name: Run Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./conexion_VPC

      # Eliminar el archivo terraform_state desde S3 (si es necesario)
      - name: Delete Terraform State File from S3
        run: |
          echo "Deleting terraform_state from S3..."
          aws s3 rm s3://artefacto-tf/terraform_state.tfstate || { echo "Failed to delete terraform_state.tfstate from S3"; exit 1; }
