name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: Clave SSH
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}"

      # Descargar el artefacto terraform_state.tfstate
      - name: Download Terraform State Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform_state  # Coincide con el nombre en el workflow de subida
          path: ./conexion_VPC

      # Renombrar el archivo descargado para que Terraform lo reconozca
      - name: Rename State File
        run: mv ./conexion_VPC/terraform_state.tfstate ./conexion_VPC/terraform.tfstate

      - name: Terraform Init
        run: terraform init
        working-directory: ./conexion_VPC

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./conexion_VPC
